language: julia
os:
  - linux
julia:
  - 0.4
  - 0.5
  - nightly
before_install:  
  - sudo apt-get -qq update
  - sudo apt-get install -y python-sympy
  - sudo apt-get install -y python-numpy
  - sudo apt-get install -y python-gmpy
  - sudo apt-get install -y python-mpmath
notifications:
  email: false
