language: julia
os:
  - linux
julia:
  - 0.4
  - 0.5
  - nightly
before_install:  
  - sudo apt-get -qq update
  - sudo apt-get install -y python-mpmath  
  - sudo apt-get install -y python-sympy

notifications:
  email: false
